apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
  labels:
    app: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
        - name: api1
          image: api1:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
